In [33]:
import pandas as pd
from pathlib import Path

In [34]:
base=pd.read_csv('data/data_clean/country_year_sanctions.csv')
base["year"] = pd.to_datetime(base["year"].astype(str).str[:4], format="%Y")
df= pd.read_csv('data/data_raw/OrganizedViolenceCYDataSet26_1.csv')
df["year"] = pd.to_datetime(df["year"].astype(str), format="%Y")

In [35]:
base

,gwcode,gw_name,microstate,year,ccode,gwc,iso3c,successor_iso3c,n_conflicts_all,n_conflicts_intra,...,n_financial_received,n_travel_received,n_other_received,num_targets_sanctioned,n_arms_sent,n_military_sent,n_trade_sent,n_financial_sent,n_travel_sent,n_other_sent
0,2,United States of America,0,1946-01-01,2.0,USA,USA,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,United States of America,0,1947-01-01,2.0,USA,USA,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,United States of America,0,1948-01-01,2.0,USA,USA,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2,United States of America,0,1949-01-01,2.0,USA,USA,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2,United States of America,0,1950-01-01,2.0,USA,USA,NaN,1,0,...,0.0,0.0,0.0,11.0,0.0,0.0,10.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12305,990,Samoa/Western Samoa,1,2019-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,15.0,13.0,9.0,2.0,11.0,12.0,3.0
12306,990,Samoa/Western Samoa,1,2020-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,15.0,13.0,9.0,2.0,11.0,12.0,3.0
12307,990,Samoa/Western Samoa,1,2021-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,16.0,13.0,9.0,2.0,12.0,12.0,3.0
12308,990,Samoa/Western Samoa,1,2022-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,17.0,14.0,9.0,2.0,13.0,13.0,3.0
12309,990,Samoa/Western Samoa,1,2023-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,17.0,13.0,8.0,2.0,13.0,13.0,3.0

In [36]:
df

,country,country_id,year,region,govt_name,sb_exist,sb_dyad_count,sb_dyad_ids,sb_dyad_names,sb_deaths_parties,...,os_total_deaths_best,os_total_deaths_high,os_total_deaths_low,cumulative_total_deaths_parties_in_orgvio,cumulative_total_deaths_civilians_in_orgvio,cumulative_total_deaths_unknown_in_orgvio,cumulative_total_deaths_in_orgvio_best,cumulative_total_deaths_in_orgvio_high,cumulative_total_deaths_in_orgvio_low,Version
0,Afghanistan,700,1989-01-01,Asia,Government of Afghanistan,1,5,724; 726; 727; 729; 732,Government of Afghanistan - Hizb-i Islami-yi A...,1019,...,0,0,0,1065,303,4043,5411,17642,2141,26.1
1,Afghanistan,700,1990-01-01,Asia,Government of Afghanistan,1,5,724; 726; 727; 732; 733,Government of Afghanistan - Hizb-i Islami-yi A...,704,...,0,0,0,724,101,689,1514,2311,1359,26.1
2,Afghanistan,700,1991-01-01,Asia,Government of Afghanistan,1,4,724; 726; 727; 732,Government of Afghanistan - Hizb-i Islami-yi A...,2274,...,0,0,0,2274,49,1230,3553,4053,3407,26.1
3,Afghanistan,700,1992-01-01,Asia,Government of Afghanistan,1,4,724; 726; 727; 732,Government of Afghanistan - Hizb-i Islami-yi A...,187,...,8,304,8,187,1695,2503,4385,5865,4368,26.1
4,Afghanistan,700,1993-01-01,Asia,Government of Afghanistan,1,4,726; 732; 734; 842,Government of Afghanistan - Hizb-i Islami-yi A...,554,...,26,240,26,556,637,2912,4105,8433,4097,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7127,Zimbabwe (Rhodesia),552,2021-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,0,0,0,0,0,0,0,0,0,26.1
7128,Zimbabwe (Rhodesia),552,2022-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,0,0,0,0,0,0,0,0,0,26.1
7129,Zimbabwe (Rhodesia),552,2023-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,0,0,0,0,0,0,0,0,0,26.1
7130,Zimbabwe (Rhodesia),552,2024-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,0,0,0,0,0,0,0,0,0,26.1
7131,Zimbabwe (Rhodesia),552,2025-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,0,0,0,0,0,0,0,0,0,26.1

In [37]:
df.columns

Index(['country', 'country_id', 'year', 'region', 'govt_name', 'sb_exist',
       'sb_dyad_count', 'sb_dyad_ids', 'sb_dyad_names', 'sb_deaths_parties',
       'sb_deaths_civilians', 'sb_deaths_unknown', 'sb_total_deaths_best',
       'sb_total_deaths_high', 'sb_total_deaths_low', 'sb_intrastate_exist',
       'sb_intrastate_dyad_count', 'sb_intrastate_dyad_ids',
       'sb_intrastate_dyad_names', 'sb_intrastate_govt_inv_incomp',
       'sb_intrastate_deaths_parties', 'sb_intrastate_deaths_civilians',
       'sb_intrastate_deaths_unknown', 'sb_intrastate_deaths_best',
       'sb_intrastate_deaths_high', 'sb_intrastate_deaths_low',
       'sb_interstate_exist', 'sb_interstate_dyad_count',
       'sb_interstate_dyad_ids', 'sb_interstate_dyad_names',
       'sb_interstate_govt_inv_incomp', 'sb_interstate_deaths_parties',
       'sb_interstate_deaths_civilians', 'sb_interstate_deaths_unknown',
       'sb_interstate_deaths_best', 'sb_interstate_deaths_high',
       'sb_interstate_deaths_low', 'ns_exist', 'ns_dyad_count', 'ns_dyad_ids',
       'ns_dyad_names', 'ns_deaths_parties', 'ns_deaths_civilians',
       'ns_deaths_unknown', 'ns_total_deaths_best', 'ns_total_deaths_high',
       'ns_total_deaths_low', 'os_exist', 'os_dyad_count', 'os_dyad_ids',
       'os_dyad_names', 'os_govt_inv', 'os_govt_killings_best',
       'os_govt_killings_high', 'os_govt_killings_low', 'os_any_govt_inv',
       'os_any_govt_killings_best', 'os_any_govt_killings_high',
       'os_any_govt_killings_low', 'os_nsgroup_inv',
       'os_nsgroup_killings_best', 'os_nsgroup_killings_high',
       'os_nsgroup_killings_low', 'os_killings_unknown',
       'os_total_deaths_best', 'os_total_deaths_high', 'os_total_deaths_low',
       'cumulative_total_deaths_parties_in_orgvio',
       'cumulative_total_deaths_civilians_in_orgvio',
       'cumulative_total_deaths_unknown_in_orgvio',
       'cumulative_total_deaths_in_orgvio_best',
       'cumulative_total_deaths_in_orgvio_high',
       'cumulative_total_deaths_in_orgvio_low', 'Version'],
      dtype='str')

In [38]:
merged = pd.merge(
    df, base,
    how='left',
    left_on=['year', 'country_id'], right_on=['year', 'gwcode'],
    indicator=True
)
orphans = merged[merged['_merge'] == 'left_only']
orphans

,country,country_id,year,region,govt_name,sb_exist,sb_dyad_count,sb_dyad_ids,sb_dyad_names,sb_deaths_parties,...,n_travel_received,n_other_received,num_targets_sanctioned,n_arms_sent,n_military_sent,n_trade_sent,n_financial_sent,n_travel_sent,n_other_sent,_merge
35,Afghanistan,700,2024-01-01,Asia,Government of Afghanistan,1,6,12287; 12291; 14320; 16825; 17083; 857,Government of Afghanistan - AFF; Government of...,141,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
36,Afghanistan,700,2025-01-01,Asia,Government of Afghanistan,1,6,12291; 14320; 16825; 17083; 18458; 857,Government of Afghanistan - AFF; Government of...,163,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
72,Albania,339,2024-01-01,Europe,Government of Albania,0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
73,Albania,339,2025-01-01,Europe,Government of Albania,0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
109,Algeria,615,2024-01-01,Africa,Government of Algeria,1,1,14847,Government of Algeria - IS,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7055,Yemen (North Yemen),678,2025-01-01,Middle East,Government of Yemen (North Yemen),1,5,14595; 14609; 16617; 17738; 18195,Government of Israel - Government of Yemen (No...,820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7093,Zambia,551,2024-01-01,Africa,Government of Zambia,0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7094,Zambia,551,2025-01-01,Africa,Government of Zambia,0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7130,Zimbabwe (Rhodesia),552,2024-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7131,Zimbabwe (Rhodesia),552,2025-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [39]:
df.loc[(df['country_id']==345) & (df['year'] > pd.Timestamp('2006-01-01')), 'country_id'] = 340

In [40]:
merged = pd.merge(
    df, base,
    how='left',
    left_on=['year', 'country_id'], right_on=['year', 'gwcode'],
    indicator=True
)
orphans = merged[merged['_merge'] == 'left_only']
orphans

,country,country_id,year,region,govt_name,sb_exist,sb_dyad_count,sb_dyad_ids,sb_dyad_names,sb_deaths_parties,...,n_travel_received,n_other_received,num_targets_sanctioned,n_arms_sent,n_military_sent,n_trade_sent,n_financial_sent,n_travel_sent,n_other_sent,_merge
35,Afghanistan,700,2024-01-01,Asia,Government of Afghanistan,1,6,12287; 12291; 14320; 16825; 17083; 857,Government of Afghanistan - AFF; Government of...,141,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
36,Afghanistan,700,2025-01-01,Asia,Government of Afghanistan,1,6,12291; 14320; 16825; 17083; 18458; 857,Government of Afghanistan - AFF; Government of...,163,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
72,Albania,339,2024-01-01,Europe,Government of Albania,0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
73,Albania,339,2025-01-01,Europe,Government of Albania,0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
109,Algeria,615,2024-01-01,Africa,Government of Algeria,1,1,14847,Government of Algeria - IS,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7055,Yemen (North Yemen),678,2025-01-01,Middle East,Government of Yemen (North Yemen),1,5,14595; 14609; 16617; 17738; 18195,Government of Israel - Government of Yemen (No...,820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7093,Zambia,551,2024-01-01,Africa,Government of Zambia,0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7094,Zambia,551,2025-01-01,Africa,Government of Zambia,0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7130,Zimbabwe (Rhodesia),552,2024-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7131,Zimbabwe (Rhodesia),552,2025-01-01,Africa,Government of Zimbabwe (Rhodesia),0,0,NO_DYAD,NO_DYAD,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [41]:
conflict_vars = [
    # Identifiers
    'country',
    'country_id',
    'year',
    'region',
    'govt_name',

    # Existence flags (any violence occurred, by type)
    'sb_exist',
    'sb_intrastate_exist',
    'sb_interstate_exist',
    'ns_exist',
    'os_exist',

    # Government involvement (relevant to sanctions -> regime repression channel)
    'sb_intrastate_govt_inv_incomp',
    'sb_interstate_govt_inv_incomp',
    'os_govt_inv',
    'os_any_govt_inv',

    # Dyad/actor counts (fragmentation of conflict, separate from intensity)
    'sb_dyad_count',
    'sb_intrastate_dyad_count',
    'sb_interstate_dyad_count',
    'ns_dyad_count',
    'os_dyad_count',

    # Cumulative totals (all violence types combined), by victim type
    'cumulative_total_deaths_parties_in_orgvio',
    'cumulative_total_deaths_civilians_in_orgvio',
    'cumulative_total_deaths_unknown_in_orgvio',
    'cumulative_total_deaths_in_orgvio_best',

    # State-based violence, by victim type
    'sb_deaths_parties',
    'sb_deaths_civilians',
    'sb_deaths_unknown',
    'sb_total_deaths_best',

    # State-based intrastate, by victim type
    'sb_intrastate_deaths_parties',
    'sb_intrastate_deaths_civilians',
    'sb_intrastate_deaths_unknown',
    'sb_intrastate_deaths_best',

    # State-based interstate, by victim type
    'sb_interstate_deaths_parties',
    'sb_interstate_deaths_civilians',
    'sb_interstate_deaths_unknown',
    'sb_interstate_deaths_best',

    # Non-state violence, by victim type
    'ns_deaths_parties',
    'ns_deaths_civilians',
    'ns_deaths_unknown',
    'ns_total_deaths_best',

    # One-sided violence, by perpetrator
    'os_govt_killings_best',
    'os_any_govt_killings_best',
    'os_nsgroup_killings_best',
    'os_killings_unknown',
    'os_total_deaths_best',
]

conflict_to_merge = df[conflict_vars]

In [42]:
base_conflict=pd.merge(base, conflict_to_merge, how='left',
    left_on=['year','gwcode'], right_on=['year',  'country_id'])

base_conflict

,gwcode,gw_name,microstate,year,ccode,gwc,iso3c,successor_iso3c,n_conflicts_all,n_conflicts_intra,...,sb_interstate_deaths_best,ns_deaths_parties,ns_deaths_civilians,ns_deaths_unknown,ns_total_deaths_best,os_govt_killings_best,os_any_govt_killings_best,os_nsgroup_killings_best,os_killings_unknown,os_total_deaths_best
0,2,United States of America,0,1946-01-01,2.0,USA,USA,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,United States of America,0,1947-01-01,2.0,USA,USA,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,United States of America,0,1948-01-01,2.0,USA,USA,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,United States of America,0,1949-01-01,2.0,USA,USA,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,United States of America,0,1950-01-01,2.0,USA,USA,NaN,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12305,990,Samoa/Western Samoa,1,2019-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12306,990,Samoa/Western Samoa,1,2020-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12307,990,Samoa/Western Samoa,1,2021-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12308,990,Samoa/Western Samoa,1,2022-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12309,990,Samoa/Western Samoa,1,2023-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
# columns you don't want to fillna with 0 (they're strings/labels, not counts)
non_numeric_cols = ['country', 'region', 'govt_name', 'year', 'country_id']

# numeric columns to zero-fill
numeric_conflict_vars = [c for c in conflict_vars if c not in non_numeric_cols]

mask = base_conflict['year'] > pd.Timestamp('1988-01-01')
base_conflict.loc[mask, numeric_conflict_vars] = base_conflict.loc[mask, numeric_conflict_vars].fillna(0)

In [44]:
base_conflict[numeric_conflict_vars]

,sb_exist,sb_intrastate_exist,sb_interstate_exist,ns_exist,os_exist,sb_intrastate_govt_inv_incomp,sb_interstate_govt_inv_incomp,os_govt_inv,os_any_govt_inv,sb_dyad_count,...,sb_interstate_deaths_best,ns_deaths_parties,ns_deaths_civilians,ns_deaths_unknown,ns_total_deaths_best,os_govt_killings_best,os_any_govt_killings_best,os_nsgroup_killings_best,os_killings_unknown,os_total_deaths_best
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12305,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12306,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12307,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12308,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12309,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
print(base_conflict['pwtpop'].describe())

count    11522.000000
mean        30.065924
std        110.684371
min          0.009545
25%          1.765020
50%          6.483040
75%         19.278560
max       1404.604076
Name: pwtpop, dtype: float64

In [46]:
# columns that should NOT be divided by population (binary existence/involvement flags)
binary_flags = [
    'sb_exist', 'sb_intrastate_exist', 'sb_interstate_exist',
    'ns_exist', 'os_exist',
    'sb_intrastate_govt_inv_incomp', 'sb_interstate_govt_inv_incomp',
    'os_govt_inv', 'os_any_govt_inv',
]

# columns to actually convert to per-capita (counts and death totals)
vars_to_percap = [c for c in numeric_conflict_vars if c not in binary_flags]

# pwtpop is in millions, so:
# deaths / pwtpop           -> deaths per million
# deaths / pwtpop / 10      -> deaths per 100,000  (equivalent to (deaths / (pwtpop * 1_000_000)) * 100_000)

for col in vars_to_percap:
    base_conflict[f'{col}_pc'] = (
        base_conflict[col].fillna(0) / base_conflict['pwtpop'] / 10
    )

/var/folders/13/671_v3jd3fb5x5kcvpwmqz800000gn/T/ipykernel_5157/1067866204.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base_conflict[f'{col}_pc'] = (

In [47]:
base_conflict

,gwcode,gw_name,microstate,year,ccode,gwc,iso3c,successor_iso3c,n_conflicts_all,n_conflicts_intra,...,sb_interstate_deaths_best_pc,ns_deaths_parties_pc,ns_deaths_civilians_pc,ns_deaths_unknown_pc,ns_total_deaths_best_pc,os_govt_killings_best_pc,os_any_govt_killings_best_pc,os_nsgroup_killings_best_pc,os_killings_unknown_pc,os_total_deaths_best_pc
0,2,United States of America,0,1946-01-01,2.0,USA,USA,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,United States of America,0,1947-01-01,2.0,USA,USA,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,United States of America,0,1948-01-01,2.0,USA,USA,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2,United States of America,0,1949-01-01,2.0,USA,USA,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2,United States of America,0,1950-01-01,2.0,USA,USA,NaN,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12305,990,Samoa/Western Samoa,1,2019-01-01,990.0,WSM,WSM,NaN,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12306,990,Samoa/Western Samoa,1,2020-01-01,990.0,WSM,WSM,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12307,990,Samoa/Western Samoa,1,2021-01-01,990.0,WSM,WSM,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12308,990,Samoa/Western Samoa,1,2022-01-01,990.0,WSM,WSM,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12309,990,Samoa/Western Samoa,1,2023-01-01,990.0,WSM,WSM,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
output_dir = Path('data/data_clean')
output_dir.mkdir(parents=True, exist_ok=True)

base_conflict.to_csv(output_dir / 'country_year_sanctions_coflict.csv', index=False)