In [20]:
# Load the packages for use
library(tidyverse)
library(peacesciencer)
library(reticulate)
library(countrycode)
library(dplyr)
library(states)
data(gwstates)

Attaching package: ‘states’


The following object is masked from ‘package:readr’:

    parse_date

In [2]:
data(ucdp_acd)
View(ucdp_acd)

     conflict_id year gwno_a gwno_a_2nd gwno_b gwno_b_2nd incompatibility
1    11342       2012 750     NA         NA     NA        territory
2    11342       2014 750     NA         NA     NA        territory
3    11343       1967 651     NA        666     NA        territory
4    11343       1969 651     NA        666     NA        territory
5    11343       1970 651     NA        666     NA        territory
6    11343       1973 651     NA        666     NA        territory
7    11344       2011 625     NA         NA     NA        territory
8    11345       2011 626     NA         NA     NA        government
9    11345       2012 626     NA         NA     NA        government
10   11345       2013 626     NA         NA     NA        government
11   11345       2014 626    500         NA     NA        government
12   11345       2015 626    500         NA     NA        government
13   11345       2016 626     NA         NA     NA        government
14   11345       2017 626     NA         NA     NA        government
15   11345       2018 626     NA         NA     NA        government
16   11345       2019 626     NA         NA     NA        government
17   11345       2020 626     NA         NA     NA        government
18   11345       2021 626     NA         NA     NA        government
19   11346       2011 620    552         NA     NA        government
20   11346       2013 620     NA         NA     NA        government
21   11346       2014 620     NA         NA     NA        government
22   11346       2015 620     NA         NA     NA        government
23   11346       2017 620     NA         NA     NA        government
24   11346       2019 620     NA         NA    625        government
25   11346       2019 620     NA         NA    696        government
26   11346       2020 620    640         NA     NA        government
27   11347       2009 432     NA         NA     NA        government
28   11347       2012 432     NA         NA     NA        government
29   11347       2013 432      2         NA     NA        government
30   11347       2013 432    200         NA     NA        government
⋮    ⋮           ⋮    ⋮      ⋮          ⋮      ⋮          ⋮
5623 432         2012 365     NA         NA    NA         territory
5624 432         2013 365     NA         NA    NA         territory
5625 432         2014 365     NA         NA    NA         territory
5626 432         2015 365     NA         NA    NA         territory
5627 434         2008 750     NA         NA    NA         territory
5628 435         2008 522     NA        531    NA         territory
5629 436         1977 530     NA         NA    NA         territory
5630 436         1978 530     NA         NA    NA         territory
5631 436         1979 530     NA         NA    NA         territory
5632 436         1980 530     40         NA    NA         territory
5633 437         1981 530     NA         NA    NA         territory
5634 437         1983 530     NA         NA    NA         territory
5635 439         2009 775     NA         NA    NA         territory
5636 439         2014 775     NA         NA    NA         territory
5637 439         2015 775     NA         NA    NA         territory
5638 439         2017 775     NA         NA    NA         territory
5639 439         2021 775     NA         NA    NA         territory
5640 439         2023 775     NA         NA    NA         territory
5641 439         2024 775     NA         NA    NA         territory
5642 440         1973 775     NA         NA    NA         territory
5643 440         1974 775     NA         NA    NA         territory
5644 440         1975 775     NA         NA    NA         territory
5645 440         1976 775     NA         NA    NA         territory
5646 440         1977 775     NA         NA    NA         territory
5647 440         1978 775     NA         NA    NA         territory
5648 440         1979 775     NA         NA    NA         territory
5649 440         1980 775     NA         NA    NA         territory
5650 440         1981 775     NA         NA    NA         territory
5651 440         1982 775     NA         NA    NA         territory
5652 442         2010 435    220         NA    NA         government
     intensity_level type_of_conflict start_date start_prec start_date2
1    1               intrastate       1997-05-29 1          2012-11-15
2    1               intrastate       1997-05-29 1          2014-07-01
3    2               interstate       1967-06-05 1          1967-06-05
4    1               interstate       1967-06-05 1          1969-03-06
5    1               interstate       1967-06-05 1          1969-03-06
6    2               interstate       1967-06-05 1          1973-10-06
7    1               intrastate       2011-05-01 1          2011-05-19
8    1               intrastate       2011-08-20 2          2011-08-20
9    1               intrastate       2011-08-20 2          2011-08-20
10   1               intrastate       2011-08-20 2          2011-08-20
11   2               II               2011-08-20 2          2011-08-20
12   1               II               2011-08-20 2          2011-08-20
13   1               intrastate       2011-08-20 2          2011-08-20
14   1               intrastate       2011-08-20 2          2011-08-20
15   1               intrastate       2011-08-20 2          2011-08-20
16   1               intrastate       2011-08-20 2          2011-08-20
17   1               intrastate       2011-08-20 2          2011-08-20
18   1               intrastate       2011-08-20 2          2011-08-20
19   2               II               2011-02-28 1          2011-03-04
20   1               intrastate       2011-02-28 1          2013-11-29
21   1               intrastate       2011-02-28 1          2013-11-29
22   1               intrastate       2011-02-28 1          2013-11-29
23   1               intrastate       2011-02-28 1          2017-05-18
24   2               II               2011-02-28 1          2019-02-21
25   2               II               2011-02-28 1          2019-02-21
26   1               II               2011-02-28 1          2019-02-21
27   1               intrastate       2009-06-10 1          2009-06-16
28   1               intrastate       2009-06-10 1          2012-01-24
29   1               II               2009-06-10 1          2012-01-24
30   1               II               2009-06-10 1          2012-01-24
⋮    ⋮               ⋮                ⋮          ⋮          ⋮
5623 1               intrastate       2007-10-07 1          2007-11-28
5624 1               intrastate       2007-10-07 1          2007-11-28
5625 1               intrastate       2007-10-07 1          2007-11-28
5626 1               intrastate       2007-10-07 1          2007-11-28
5627 1               intrastate       2000-06-20 1          2008-12-04
5628 1               interstate       2008-06-10 1          2008-06-11
5629 1               intrastate       1977-12-31 5          1977-12-31
5630 1               intrastate       1977-12-31 5          1977-12-31
5631 1               intrastate       1977-12-31 5          1977-12-31
5632 1               II               1977-12-31 5          1977-12-31
5633 2               intrastate       1981-03-21 2          1981-03-21
5634 1               intrastate       1981-03-21 2          1983-03-16
5635 1               intrastate       2009-08-27 1          2009-08-29
5636 1               intrastate       2009-08-27 1          2014-12-22
5637 1               intrastate       2009-08-27 1          2014-12-22
5638 1               intrastate       2009-08-27 1          2017-03-06
5639 1               intrastate       2009-08-27 1          2021-08-28
5640 1               intrastate       2009-08-27 1          2023-11-22
5641 1               intrastate       2009-08-27 1          2023-11-22
5642 1               intrastate       1973-01-11 2          1973-02-28
5643 1               intrastate       1973-01-11 2          1973-02-28
5644 1               intrastate       1973-01-11 2          1973-02-28
5645 1               intrastate       1973-01-11 2          1973-02-28
5646 1               intrastate       1973-01-11 2          1973-02-28
5647 1               intrastate       1973-01-11 2          1973-02-28
5648 1               intrastate       1973-01-11 2          1973-02-28
5649 1               intrastate       1973-01-11 2          1973-02-28
5650 1               intrastate       1973-01-11 2          1973-02-28
5651 1               intrastate       1973-01-11 2          1973-02-28
5652 1               II               2008-09-15 1          2010-09-18
     start_prec2 ep_end ep_end_date
1    1           1      2012-12-21
2    1           1      2014-11-27
3    1           1      1967-06-10
4    1           0      <NA>
5    1           1      1970-08-07
6    1           1      1973-10-24
7    1           1      2011-06-15
8    2           0      <NA>
9    2           0      <NA>
10   2           0      <NA>
11   2           0      <NA>
12   2           0      <NA>
13   2           0      <NA>
14   2           0      <NA>
15   2           0      <NA>
16   2           0      <NA>
17   2           0      <NA>
18   2           1      2021-12-27
19   1           1      2011-11-23
20   1           0      <NA>
21   1           0      <NA>
22   1           1      2015-04-19
23   1           1      2017-11-12
24   2           0      <NA>
25   2           0      <NA>
26   2           1      2020-10-31
27   1           1      2009-07-16
28   1           0      <NA>
29   1           0      <NA>
30   1           0      <NA>
⋮    ⋮           ⋮      ⋮
5623 1           0      <NA>
5624 1           0      <NA>
5625 1           0      <NA>
5626 1           1      2015-10-21
5627 1           1      2008-12-22
5628 2           1      2008-06-11
5629 5           0      <NA>
5630 5           0      <NA>
5631 5           0      <NA>
5632 5           1      1980-12-31
5633 2           1      1981-03-21
5634 1           1      1983-12-31
5635 2           1      2009-12-31
5636 5           0      <NA>
5637 5           1      2015-12-19
5638 1           1      2017-03-12
5639 1           1      2021-12-26
5640 1           0      <NA>
5641 1           0      <NA>
5642 4           0      <NA>
5643 4           0      <NA>
5644 4           0      <NA>
5645 4           0      <NA>
5646 4           0      <NA>
5647 4           0      <NA>
5648 4           0      <NA>
5649 4           0      <NA>
5650 4           0      <NA>
5651 4           1      1982-12-31
5652 2           1      2010-09-18

In [ ]:
base <- create_stateyears(system = "gw", subset_years = c(1946:2023)) %>%
  add_ccode_to_gw() %>%
  left_join(
    gwstates %>% select(gwcode, gwc, start, end),
    by = "gwcode",
    relationship = "many-to-many"
  ) %>%
  filter(year >= year(start) & year <= year(end)) %>%
  select(-start, -end)%>%
  mutate(iso3c = countrycode(gwcode, "gwn", "iso3c"))
 
base <- base %>%
  mutate(
    gw_name = case_when(
      gwcode == 403 ~ "Sao Tome and Principe",  # São Tomé and Príncipe
      gwcode == 437 ~ "Ivory Coast",                     # Côte d'Ivoire
      TRUE ~ gw_name
    )
  )

View(base)

Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `iso3c = countrycode(gwcode, "gwn", "iso3c")`.
Caused by warning:
! Some values were not matched unambiguously: 54, 55, 56, 57, 58, 60, 221, 223, 232, 265, 315, 331, 345, 347, 396, 397, 403, 511, 591, 678, 680, 711, 816, 817, 935, 970, 971, 972, 973, 983, 986, 987, 990
To fix unmatched values, please use the `custom_match` argument. If you think the default matching rules should be improved, please file an issue at https://github.com/vincentarelbundock/countrycode/issues”

      gwcode gw_name                  microstate year ccode gwc iso3c
1     2      United States of America 0          1946 2     USA USA
2     2      United States of America 0          1947 2     USA USA
3     2      United States of America 0          1948 2     USA USA
4     2      United States of America 0          1949 2     USA USA
5     2      United States of America 0          1950 2     USA USA
6     2      United States of America 0          1951 2     USA USA
7     2      United States of America 0          1952 2     USA USA
8     2      United States of America 0          1953 2     USA USA
9     2      United States of America 0          1954 2     USA USA
10    2      United States of America 0          1955 2     USA USA
11    2      United States of America 0          1956 2     USA USA
12    2      United States of America 0          1957 2     USA USA
13    2      United States of America 0          1958 2     USA USA
14    2      United States of America 0          1959 2     USA USA
15    2      United States of America 0          1960 2     USA USA
16    2      United States of America 0          1961 2     USA USA
17    2      United States of America 0          1962 2     USA USA
18    2      United States of America 0          1963 2     USA USA
19    2      United States of America 0          1964 2     USA USA
20    2      United States of America 0          1965 2     USA USA
21    2      United States of America 0          1966 2     USA USA
22    2      United States of America 0          1967 2     USA USA
23    2      United States of America 0          1968 2     USA USA
24    2      United States of America 0          1969 2     USA USA
25    2      United States of America 0          1970 2     USA USA
26    2      United States of America 0          1971 2     USA USA
27    2      United States of America 0          1972 2     USA USA
28    2      United States of America 0          1973 2     USA USA
29    2      United States of America 0          1974 2     USA USA
30    2      United States of America 0          1975 2     USA USA
⋮     ⋮      ⋮                        ⋮          ⋮    ⋮     ⋮   ⋮
12281 990    Samoa/Western Samoa      1          1994 990   WSM NA
12282 990    Samoa/Western Samoa      1          1995 990   WSM NA
12283 990    Samoa/Western Samoa      1          1996 990   WSM NA
12284 990    Samoa/Western Samoa      1          1997 990   WSM NA
12285 990    Samoa/Western Samoa      1          1998 990   WSM NA
12286 990    Samoa/Western Samoa      1          1999 990   WSM NA
12287 990    Samoa/Western Samoa      1          2000 990   WSM NA
12288 990    Samoa/Western Samoa      1          2001 990   WSM NA
12289 990    Samoa/Western Samoa      1          2002 990   WSM NA
12290 990    Samoa/Western Samoa      1          2003 990   WSM NA
12291 990    Samoa/Western Samoa      1          2004 990   WSM NA
12292 990    Samoa/Western Samoa      1          2005 990   WSM NA
12293 990    Samoa/Western Samoa      1          2006 990   WSM NA
12294 990    Samoa/Western Samoa      1          2007 990   WSM NA
12295 990    Samoa/Western Samoa      1          2008 990   WSM NA
12296 990    Samoa/Western Samoa      1          2009 990   WSM NA
12297 990    Samoa/Western Samoa      1          2010 990   WSM NA
12298 990    Samoa/Western Samoa      1          2011 990   WSM NA
12299 990    Samoa/Western Samoa      1          2012 990   WSM NA
12300 990    Samoa/Western Samoa      1          2013 990   WSM NA
12301 990    Samoa/Western Samoa      1          2014 990   WSM NA
12302 990    Samoa/Western Samoa      1          2015 990   WSM NA
12303 990    Samoa/Western Samoa      1          2016 990   WSM NA
12304 990    Samoa/Western Samoa      1          2017 990   WSM NA
12305 990    Samoa/Western Samoa      1          2018 990   WSM NA
12306 990    Samoa/Western Samoa      1          2019 990   WSM NA
12307 990    Samoa/Western Samoa      1          2020 990   WSM NA
12308 990    Samoa/Western Samoa      1          2021 990   WSM NA
12309 990    Samoa/Western Samoa      1          2022 990   WSM NA
12310 990    Samoa/Western Samoa      1          2023 990   WSM NA

In [37]:
# --- Step 2: living microstates countrycode just misses (safe hard-code) ---
manual_iso3 <- c(
  # microstates countrycode just misses
  "54"  = "DMA", "55" = "GRD", "56" = "LCA", "57" = "VCT", "58" = "ATG", "60" = "KNA",
  "221" = "MCO", "223" = "LIE", "232" = "AND", "331" = "SMR", "591" = "SYC",
  "935" = "VUT", "970" = "KIR", "971" = "NRU", "972" = "TON", "973" = "TUV",
  "983" = "MHL", "986" = "PLW", "987" = "FSM", "990" = "WSM",
  "403" = "STP", "437" = "CIV",
  # historical states' own period ISO3 (not a successor mapping)
  "315" = "CSK",  # Czechoslovakia
  "265" = "DDR",  # East Germany
  "345" = "YUG",  # Yugoslavia (SFRY)
  "680" = "YMD",  # South Yemen (People's Democratic Republic)
  "678" = "YEM",  # North Yemen (Yemen Arab Republic) — kept the continuing code
  "816" = "VDR",  # North Vietnam (Democratic Republic) — distinct retired code
  "817" = "VNM",   # South Vietnam (Republic of) — kept the continuing code
  "347" = "KSV"   # Kosovo
)

base <- base %>%
  mutate(iso3c = if_else(
    is.na(iso3c) & as.character(gwcode) %in% names(manual_iso3),
    manual_iso3[as.character(gwcode)],
    iso3c
  ))

# --- Step 3: historical/dissolved states — no living ISO3, keep iso3c as NA, 
#     but add a SEPARATE successor_iso3c column for merges that need one ---
successor_map <- c(
  "265" = "DEU",  # East Germany -> Germany
  "260" = "DEU",  # West Germany -> Germany
  "315" = "CZE",  # Czechoslovakia -> Czechia (judgment call; could split CZE/SVK by year if needed)
  "345" = "SRB",  # Yugoslavia -> Serbia (Miller's convention; revisit if your DV is territorial)
  "680" = "YEM",  # South Yemen -> Yemen
  "711" = "CHN",  # Tibet -> China (if relevant to your scope)
  "817" = "VNM",  # South Vietnam -> Vietnam
  "347" = "XKX"   # Kosovo -- only if your other sources use this convention
)

base <- base %>%
  mutate(successor_iso3c = if_else(
    as.character(gwcode) %in% names(successor_map),
    successor_map[as.character(gwcode)],
    NA_character_
  ))

# --- Step 5: final check ---
base %>% filter(is.na(iso3c)) %>% distinct(gwcode, gw_name)
# should only show: Abkhazia (396), South Ossetia (397), and any others 
# with genuinely no ISO3/successor convention — leave these as NA

  gwcode gw_name
1 396    Abkhazia
2 397    South Ossetia
3 511    Zanzibar
4 711    Tibet

In [38]:
write.csv(base, "base.csv", row.names = FALSE)

In [30]:
# --- Step 2: check what's left unmatched ---
base %>%
  distinct(gwcode, gw_name, iso3c) %>%
  filter(is.na(iso3c)) %>%
  arrange(gwcode)

   gwcode gw_name                          iso3c
1   54    Dominica                         NA
2   55    Grenada                          NA
3   56    Saint Lucia                      NA
4   57    Saint Vincent and the Grenadines NA
5   58    Antigua & Barbuda                NA
6   60    Saint Kitts and Nevis            NA
7  221    Monaco                           NA
8  223    Liechtenstein                    NA
9  232    Andorra                          NA
10 265    German Democratic Republic       NA
11 315    Czechoslovakia                   NA
12 331    San Marino                       NA
13 345    Yugoslavia                       NA
14 347    Kosovo                           NA
15 396    Abkhazia                         NA
16 397    South Ossetia                    NA
17 403    Sao Tome and Principe            NA
18 511    Zanzibar                         NA
19 591    Seychelles                       NA
20 678    Yemen (Arab Republic of Yemen)   NA
21 680    Yemen, People's Republic of      NA
22 711    Tibet                            NA
23 816    Vietnam, Democratic Republic of  NA
24 817    Vietnam, Republic of             NA
25 935    Vanuatu                          NA
26 970    Kiribati                         NA
27 971    Nauru                            NA
28 972    Tonga                            NA
29 973    Tuvalu                           NA
30 983    Marshall Islands                 NA
31 986    Palau                            NA
32 987    Federated States of Micronesia   NA
33 990    Samoa/Western Samoa              NA

In [17]:
base %>%
  distinct(gwcode, gwc, iso3c) %>%
  filter(is.na(iso3c) | is.na(gwc)) %>%
  arrange(gwcode)

   gwcode gwc iso3c
1   54    NA  NA
2   55    NA  NA
3   56    NA  NA
4   57    NA  NA
5   58    NA  NA
6   60    NA  NA
7  221    NA  NA
8  223    NA  NA
9  232    NA  NA
10 265    GDR NA
11 315    CZE NA
12 331    NA  NA
13 345    YUG NA
14 347    KOS NA
15 396    NA  NA
16 397    NA  NA
17 403    NA  NA
18 511    ZAN NA
19 591    NA  NA
20 678    YEM NA
21 680    YPR NA
22 711    TBT NA
23 816    NA  NA
24 817    RVN NA
25 935    NA  NA
26 970    NA  NA
27 971    NA  NA
28 972    NA  NA
29 973    NA  NA
30 983    NA  NA
31 986    NA  NA
32 987    NA  NA
33 990    NA  NA

In [42]:
# all types pooled
ucdp_acd %>%
  group_by(gwno_a, year) %>%
  summarize(n_conflicts_all = n_distinct(conflict_id)) %>%
  rename(gwcode = gwno_a) -> conflict_counts_all

# intrastate + II
ucdp_acd %>%
  filter(type_of_conflict %in% c(3,4)) %>%
  group_by(gwno_a, year) %>%
  summarize(n_conflicts_intra = n_distinct(conflict_id)) %>%
  rename(gwcode = gwno_a) -> conflict_counts_intra

# interstate
ucdp_acd %>%
  filter(type_of_conflict == 2) %>%
  group_by(gwno_a, year) %>%
  summarize(n_conflicts_inter = n_distinct(conflict_id)) %>%
  rename(gwcode = gwno_a) -> conflict_counts_inter

# extrasystemic
ucdp_acd %>%
  filter(type_of_conflict == 1) %>%
  group_by(gwno_a, year) %>%
  summarize(n_conflicts_extra = n_distinct(conflict_id)) %>%
  rename(gwcode = gwno_a) -> conflict_counts_extra

# join everything onto your state-year frame
final <- base %>%
  left_join(conflict_counts_all, by = c("gwcode", "year")) %>%
  left_join(conflict_counts_intra, by = c("gwcode", "year")) %>%
  left_join(conflict_counts_inter, by = c("gwcode", "year")) %>%
  left_join(conflict_counts_extra, by = c("gwcode", "year")) %>%
  mutate(across(starts_with("n_conflicts"), ~replace_na(.x, 0)))

final

`summarise()` has grouped output by 'gwno_a'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'gwno_a'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'gwno_a'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'gwno_a'. You can override using the
`.groups` argument.

      gwcode gw_name                  microstate year ccode gwc iso3c
1     2      United States of America 0          1946 2     USA USA
2     2      United States of America 0          1947 2     USA USA
3     2      United States of America 0          1948 2     USA USA
4     2      United States of America 0          1949 2     USA USA
5     2      United States of America 0          1950 2     USA USA
6     2      United States of America 0          1951 2     USA USA
7     2      United States of America 0          1952 2     USA USA
8     2      United States of America 0          1953 2     USA USA
9     2      United States of America 0          1954 2     USA USA
10    2      United States of America 0          1955 2     USA USA
11    2      United States of America 0          1956 2     USA USA
12    2      United States of America 0          1957 2     USA USA
13    2      United States of America 0          1958 2     USA USA
14    2      United States of America 0          1959 2     USA USA
15    2      United States of America 0          1960 2     USA USA
16    2      United States of America 0          1961 2     USA USA
17    2      United States of America 0          1962 2     USA USA
18    2      United States of America 0          1963 2     USA USA
19    2      United States of America 0          1964 2     USA USA
20    2      United States of America 0          1965 2     USA USA
21    2      United States of America 0          1966 2     USA USA
22    2      United States of America 0          1967 2     USA USA
23    2      United States of America 0          1968 2     USA USA
24    2      United States of America 0          1969 2     USA USA
25    2      United States of America 0          1970 2     USA USA
26    2      United States of America 0          1971 2     USA USA
27    2      United States of America 0          1972 2     USA USA
28    2      United States of America 0          1973 2     USA USA
29    2      United States of America 0          1974 2     USA USA
30    2      United States of America 0          1975 2     USA USA
⋮     ⋮      ⋮                        ⋮          ⋮    ⋮     ⋮   ⋮
12281 990    Samoa/Western Samoa      1          1994 990   WSM WSM
12282 990    Samoa/Western Samoa      1          1995 990   WSM WSM
12283 990    Samoa/Western Samoa      1          1996 990   WSM WSM
12284 990    Samoa/Western Samoa      1          1997 990   WSM WSM
12285 990    Samoa/Western Samoa      1          1998 990   WSM WSM
12286 990    Samoa/Western Samoa      1          1999 990   WSM WSM
12287 990    Samoa/Western Samoa      1          2000 990   WSM WSM
12288 990    Samoa/Western Samoa      1          2001 990   WSM WSM
12289 990    Samoa/Western Samoa      1          2002 990   WSM WSM
12290 990    Samoa/Western Samoa      1          2003 990   WSM WSM
12291 990    Samoa/Western Samoa      1          2004 990   WSM WSM
12292 990    Samoa/Western Samoa      1          2005 990   WSM WSM
12293 990    Samoa/Western Samoa      1          2006 990   WSM WSM
12294 990    Samoa/Western Samoa      1          2007 990   WSM WSM
12295 990    Samoa/Western Samoa      1          2008 990   WSM WSM
12296 990    Samoa/Western Samoa      1          2009 990   WSM WSM
12297 990    Samoa/Western Samoa      1          2010 990   WSM WSM
12298 990    Samoa/Western Samoa      1          2011 990   WSM WSM
12299 990    Samoa/Western Samoa      1          2012 990   WSM WSM
12300 990    Samoa/Western Samoa      1          2013 990   WSM WSM
12301 990    Samoa/Western Samoa      1          2014 990   WSM WSM
12302 990    Samoa/Western Samoa      1          2015 990   WSM WSM
12303 990    Samoa/Western Samoa      1          2016 990   WSM WSM
12304 990    Samoa/Western Samoa      1          2017 990   WSM WSM
12305 990    Samoa/Western Samoa      1          2018 990   WSM WSM
12306 990    Samoa/Western Samoa      1          2019 990   WSM WSM
12307 990    Samoa/Western Samoa      1          2020 990   WSM WSM
12308 990    Samoa/Western Samoa      1          2021 990   WSM WSM
12309 990    Samoa/Western Samoa      1          2022 990   WSM WSM
12310 990    Samoa/Western Samoa      1          2023 990   WSM WSM
      successor_iso3c n_conflicts_all n_conflicts_intra n_conflicts_inter
1     NA              0               0                 0
2     NA              0               0                 0
3     NA              0               0                 0
4     NA              0               0                 0
5     NA              1               0                 0
6     NA              0               0                 0
7     NA              0               0                 0
8     NA              0               0                 0
9     NA              0               0                 0
10    NA              0               0                 0
11    NA              0               0                 0
12    NA              0               0                 0
13    NA              0               0                 0
14    NA              0               0                 0
15    NA              0               0                 0
16    NA              0               0                 0
17    NA              0               0                 0
18    NA              0               0                 0
19    NA              0               0                 0
20    NA              0               0                 0
21    NA              0               0                 0
22    NA              0               0                 0
23    NA              0               0                 0
24    NA              0               0                 0
25    NA              0               0                 0
26    NA              0               0                 0
27    NA              0               0                 0
28    NA              0               0                 0
29    NA              0               0                 0
30    NA              0               0                 0
⋮     ⋮               ⋮               ⋮                 ⋮
12281 NA              0               0                 0
12282 NA              0               0                 0
12283 NA              0               0                 0
12284 NA              0               0                 0
12285 NA              0               0                 0
12286 NA              0               0                 0
12287 NA              0               0                 0
12288 NA              0               0                 0
12289 NA              0               0                 0
12290 NA              0               0                 0
12291 NA              0               0                 0
12292 NA              0               0                 0
12293 NA              0               0                 0
12294 NA              0               0                 0
12295 NA              0               0                 0
12296 NA              0               0                 0
12297 NA              0               0                 0
12298 NA              0               0                 0
12299 NA              0               0                 0
12300 NA              0               0                 0
12301 NA              0               0                 0
12302 NA              0               0                 0
12303 NA              0               0                 0
12304 NA              0               0                 0
12305 NA              0               0                 0
12306 NA              0               0                 0
12307 NA              0               0                 0
12308 NA              0               0                 0
12309 NA              0               0                 0
12310 NA              0               0                 0
      n_conflicts_extra
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
⋮     ⋮
12281 0
12282 0
12283 0
12284 0
12285 0
12286 0
12287 0
12288 0
12289 0
12290 0
12291 0
12292 0
12293 0
12294 0
12295 0
12296 0
12297 0
12298 0
12299 0
12300 0
12301 0
12302 0
12303 0
12304 0
12305 0
12306 0
12307 0
12308 0
12309 0
12310 0

In [44]:
final <- final %>%
add_democracy() %>%
add_sim_gdp_pop()

final

Joining with `by = join_by(gwcode, year, euds, aeuds, polity2, v2x_polyarchy)`
Joining with `by = join_by(gwcode, year, mrgdppc, sd_mrgdppc, pwtrgdp,
sd_pwtrgdp, pwtpop, sd_pwtpop)`

      gwcode gw_name                  microstate year ccode gwc iso3c
1     2      United States of America 0          1946 2     USA USA
2     2      United States of America 0          1947 2     USA USA
3     2      United States of America 0          1948 2     USA USA
4     2      United States of America 0          1949 2     USA USA
5     2      United States of America 0          1950 2     USA USA
6     2      United States of America 0          1951 2     USA USA
7     2      United States of America 0          1952 2     USA USA
8     2      United States of America 0          1953 2     USA USA
9     2      United States of America 0          1954 2     USA USA
10    2      United States of America 0          1955 2     USA USA
11    2      United States of America 0          1956 2     USA USA
12    2      United States of America 0          1957 2     USA USA
13    2      United States of America 0          1958 2     USA USA
14    2      United States of America 0          1959 2     USA USA
15    2      United States of America 0          1960 2     USA USA
16    2      United States of America 0          1961 2     USA USA
17    2      United States of America 0          1962 2     USA USA
18    2      United States of America 0          1963 2     USA USA
19    2      United States of America 0          1964 2     USA USA
20    2      United States of America 0          1965 2     USA USA
21    2      United States of America 0          1966 2     USA USA
22    2      United States of America 0          1967 2     USA USA
23    2      United States of America 0          1968 2     USA USA
24    2      United States of America 0          1969 2     USA USA
25    2      United States of America 0          1970 2     USA USA
26    2      United States of America 0          1971 2     USA USA
27    2      United States of America 0          1972 2     USA USA
28    2      United States of America 0          1973 2     USA USA
29    2      United States of America 0          1974 2     USA USA
30    2      United States of America 0          1975 2     USA USA
⋮     ⋮      ⋮                        ⋮          ⋮    ⋮     ⋮   ⋮
12281 990    Samoa/Western Samoa      1          1994 990   WSM WSM
12282 990    Samoa/Western Samoa      1          1995 990   WSM WSM
12283 990    Samoa/Western Samoa      1          1996 990   WSM WSM
12284 990    Samoa/Western Samoa      1          1997 990   WSM WSM
12285 990    Samoa/Western Samoa      1          1998 990   WSM WSM
12286 990    Samoa/Western Samoa      1          1999 990   WSM WSM
12287 990    Samoa/Western Samoa      1          2000 990   WSM WSM
12288 990    Samoa/Western Samoa      1          2001 990   WSM WSM
12289 990    Samoa/Western Samoa      1          2002 990   WSM WSM
12290 990    Samoa/Western Samoa      1          2003 990   WSM WSM
12291 990    Samoa/Western Samoa      1          2004 990   WSM WSM
12292 990    Samoa/Western Samoa      1          2005 990   WSM WSM
12293 990    Samoa/Western Samoa      1          2006 990   WSM WSM
12294 990    Samoa/Western Samoa      1          2007 990   WSM WSM
12295 990    Samoa/Western Samoa      1          2008 990   WSM WSM
12296 990    Samoa/Western Samoa      1          2009 990   WSM WSM
12297 990    Samoa/Western Samoa      1          2010 990   WSM WSM
12298 990    Samoa/Western Samoa      1          2011 990   WSM WSM
12299 990    Samoa/Western Samoa      1          2012 990   WSM WSM
12300 990    Samoa/Western Samoa      1          2013 990   WSM WSM
12301 990    Samoa/Western Samoa      1          2014 990   WSM WSM
12302 990    Samoa/Western Samoa      1          2015 990   WSM WSM
12303 990    Samoa/Western Samoa      1          2016 990   WSM WSM
12304 990    Samoa/Western Samoa      1          2017 990   WSM WSM
12305 990    Samoa/Western Samoa      1          2018 990   WSM WSM
12306 990    Samoa/Western Samoa      1          2019 990   WSM WSM
12307 990    Samoa/Western Samoa      1          2020 990   WSM WSM
12308 990    Samoa/Western Samoa      1          2021 990   WSM WSM
12309 990    Samoa/Western Samoa      1          2022 990   WSM WSM
12310 990    Samoa/Western Samoa      1          2023 990   WSM WSM
      successor_iso3c n_conflicts_all n_conflicts_intra ⋯ euds
1     NA              0               0                 ⋯ 1.293985
2     NA              0               0                 ⋯ 1.308359
3     NA              0               0                 ⋯ 1.343539
4     NA              0               0                 ⋯ 1.330836
5     NA              1               0                 ⋯ 1.354015
6     NA              0               0                 ⋯ 1.350228
7     NA              0               0                 ⋯ 1.391332
8     NA              0               0                 ⋯ 1.391332
9     NA              0               0                 ⋯ 1.383708
10    NA              0               0                 ⋯ 1.393116
11    NA              0               0                 ⋯ 1.387494
12    NA              0               0                 ⋯ 1.387494
13    NA              0               0                 ⋯ 1.379134
14    NA              0               0                 ⋯ 1.379134
15    NA              0               0                 ⋯ 1.411012
16    NA              0               0                 ⋯ 1.404158
17    NA              0               0                 ⋯ 1.428196
18    NA              0               0                 ⋯ 1.411072
19    NA              0               0                 ⋯ 1.380611
20    NA              0               0                 ⋯ 1.440751
21    NA              0               0                 ⋯ 1.432579
22    NA              0               0                 ⋯ 1.428730
23    NA              0               0                 ⋯ 1.427401
24    NA              0               0                 ⋯ 1.491867
25    NA              0               0                 ⋯ 1.442086
26    NA              0               0                 ⋯ 1.446260
27    NA              0               0                 ⋯ 1.456453
28    NA              0               0                 ⋯ 1.504923
29    NA              0               0                 ⋯ 1.670654
30    NA              0               0                 ⋯ 1.670654
⋮     ⋮               ⋮               ⋮                 ⋱ ⋮
12281 NA              0               0                 ⋯ 0.7685987
12282 NA              0               0                 ⋯ 0.7685987
12283 NA              0               0                 ⋯ 0.8131357
12284 NA              0               0                 ⋯ 0.7787918
12285 NA              0               0                 ⋯ 0.8083407
12286 NA              0               0                 ⋯ 0.7854574
12287 NA              0               0                 ⋯ 0.9122279
12288 NA              0               0                 ⋯ 0.7914217
12289 NA              0               0                 ⋯ 0.8314435
12290 NA              0               0                 ⋯ 0.8314435
12291 NA              0               0                 ⋯ 0.8314435
12292 NA              0               0                 ⋯ 0.8314435
12293 NA              0               0                 ⋯ 0.8099322
12294 NA              0               0                 ⋯ 0.8614654
12295 NA              0               0                 ⋯ 0.8614654
12296 NA              0               0                 ⋯ 0.9690240
12297 NA              0               0                 ⋯ 0.9690240
12298 NA              0               0                 ⋯ 1.0598056
12299 NA              0               0                 ⋯ 1.0421563
12300 NA              0               0                 ⋯ 1.0598056
12301 NA              0               0                 ⋯ 1.0739905
12302 NA              0               0                 ⋯ 1.0143287
12303 NA              0               0                 ⋯ 0.9242874
12304 NA              0               0                 ⋯ 0.9027581
12305 NA              0               0                 ⋯ 0.9209782
12306 NA              0               0                 ⋯ 0.8466403
12307 NA              0               0                 ⋯ 0.9888136
12308 NA              0               0                 ⋯ 1.3273295
12309 NA              0               0                 ⋯ 1.0080238
12310 NA              0               0                 ⋯        NA
      aeuds         polity2 v2x_polyarchy mrgdppc  sd_mrgdppc pwtrgdp
1     0.4862558      9      0.603         15916.61 2494.190   2565007
2     0.5006298      9      0.607         15691.61 2443.672   2524909
3     0.5358093      9      0.599         15634.17 2397.095   2621770
4     0.5231064      9      0.580         15774.79 2415.503   2724009
5     0.5462858      9      0.585         16610.07 2605.984   2831568
6     0.5424987      9      0.611         17386.07 2680.565   3084613
7     0.5836026      9      0.611         17880.30 2794.786   3186280
8     0.5836026      9      0.612         18097.87 2813.028   3280505
9     0.5759780      9      0.611         18287.42 2894.786   3368356
10    0.5853868      9      0.609         18648.72 2893.255   3533845
11    0.5797642      9      0.613         18815.01 3018.568   3679478
12    0.5797642      9      0.614         18939.92 2961.680   3731184
13    0.5714044      9      0.624         19030.56 3025.965   3726529
14    0.5714044      9      0.623         19648.00 3104.631   3885785
15    0.6032822      9      0.644         20329.47 3218.651   4123378
16    0.5964280      9      0.659         20774.26 3228.978   4450638
17    0.6204664      9      0.661         21491.85 3296.276   4543595
18    0.6033424      9      0.675         22219.33 3491.348   4771251
19    0.5728810      9      0.677         22977.23 3581.153   5040272
20    0.6330211      9      0.677         23929.71 3598.320   5384167
21    0.6248497      9      0.695         25033.56 3799.413   5668761
22    0.6210003      8      0.704         25593.83 3904.275   5817550
23    0.6196716      8      0.702         26598.50 4119.641   6148964
24    0.6841377      8      0.696         26906.73 4084.590   6289286
25    0.6343567      8      0.717         27115.78 4226.573   6359338
26    0.6385304      8      0.726         27663.26 4162.992   6563829
27    0.6487237      8      0.735         28517.91 4478.574   6880406
28    0.6971930      8      0.755         29317.10 4632.048   6962601
29    0.8629249     10      0.760         29523.46 4586.760   7327273
30    0.8629249     10      0.784         29864.52 4700.055   7361988
⋮     ⋮             ⋮       ⋮             ⋮        ⋮          ⋮
12281 -0.0391308766 NA      NA            3341.702 5044.416    629.4185
12282 -0.0391308766 NA      NA            3437.835 5125.308    669.0794
12283  0.0054061683 NA      NA            3530.554 5066.269    689.8376
12284 -0.0289377519 NA      NA            3615.825 5030.577    707.1212
12285  0.0006111145 NA      NA            3764.132 5484.485    722.0436
12286 -0.0222721880 NA      NA            3847.929 5471.900    747.2249
12287  0.1044983332 NA      NA            4015.930 5636.274    795.4182
12288 -0.0163078547 NA      NA            4240.914 6206.646    849.2132
12289  0.0237139096 NA      NA            4391.601 6351.391    888.0702
12290  0.0237139096 NA      NA            4623.238 6518.377    921.5627
12291  0.0237139096 NA      NA            4729.454 6677.319    956.4958
12292  0.0237139096 NA      NA            4891.753 6993.552   1000.6056
12293  0.0022026775 NA      NA            4988.973 7057.523   1041.1080
12294  0.0537358500 NA      NA            5164.969 7534.104   1075.4102
12295  0.0537358500 NA      NA            5174.837 7299.498   1121.8762
12296  0.1612944478 NA      NA            5224.202 7411.768   1127.8913
12297  0.1612944478 NA      NA            5201.600 7497.951   1098.6934
12298  0.2520760739 NA      NA            5227.176 7635.390   1128.5508
12299  0.2344267627 NA      NA            5178.788 7446.260   1118.1210
12300  0.2520760739 NA      NA            5127.401 7285.333   1130.3675
12301  0.2662609148 NA      NA            5076.456 7389.454   1133.4567
12302  0.2065991024 NA      NA            5031.131 7057.960   1108.9648
12303  0.1165578080 NA      NA            5236.855 7767.856   1126.3444
12304  0.0950284959 NA      NA            5179.210 7218.929   1137.1567
12305  0.1132486425 NA      NA            5260.575 7524.086   1132.2966
12306  0.0389107448 NA      NA            5280.998 7602.198   1161.9157
12307  0.1810840550 NA      NA                  NA       NA          NA
12308  0.5195999385 NA      NA                  NA       NA          NA
12309  0.2002942698 NA      NA                  NA       NA          NA
12310            NA NA      NA                  NA       NA          NA
      sd_pwtrgdp pwtpop    sd_pwtpop
1     1075414    142.9422   9.874863
2     1097010    145.6134  10.302882
3     1143350    148.4436  10.571322
4     1187962    150.5542  10.712760
5     1207133    153.5495  10.469628
6     1318417    156.0024  10.514347
7     1313776    158.6386  11.001020
8     1382091    162.0679  11.405280
9     1418385    163.9987  11.371540
10    1472963    167.1180  11.461583
11    1609803    170.1564  11.653310
12    1632490    172.7378  11.516579
13    1655302    176.3144  11.983057
14    1619264    178.9837  12.349695
15    1741912    182.9240  12.759723
16    1945194    186.0568  12.403574
17    1994732    188.9391  13.114155
18    2048485    191.2448  12.949977
19    2163412    194.0475  13.157912
20    2273499    196.6550  13.535673
21    2434069    198.8872  13.804870
22    2475062    200.9702  13.434916
23    2705345    203.4772  13.921968
24    2689907    205.6160  13.785714
25    2690756    207.8886  14.026152
26    2687985    210.5164  14.436576
27    2893094    213.2479  14.391320
28    2931703    214.5475  14.255521
29    3115422    217.0642  14.716172
30    3132008    219.3290  14.903550
⋮     ⋮          ⋮         ⋮
12281  932.7393  0.1686819 0.01218411
12282 1075.8129  0.1707519 0.01235987
12283 1122.9872  0.1728808 0.01247585
12284 1193.1618  0.1730419 0.01289318
12285 1050.8535  0.1738515 0.01308898
12286 1133.2649  0.1748782 0.01284046
12287 1347.5184  0.1760113 0.01271344
12288 1281.0947  0.1762775 0.01319021
12289 1536.1365  0.1784095 0.01309496
12290 1375.3722  0.1793477 0.01298249
12291 1432.6292  0.1802098 0.01335519
12292 1680.2374  0.1822562 0.01347284
12293 1657.6565  0.1830841 0.01322797
12294 1588.5878  0.1850700 0.01354247
12295 1966.6157  0.1862519 0.01378275
12296 1920.9780  0.1878027 0.01386005
12297 1702.0378  0.1892626 0.01367036
12298 2037.6496  0.1906959 0.01385773
12299 1783.1469  0.1921452 0.01377836
12300 1789.5205  0.1931793 0.01406151
12301 1759.7631  0.1944935 0.01397184
12302 1626.3097  0.1941076 0.01414728
12303 1677.7273  0.1945838 0.01425105
12304 1751.7423  0.1954680 0.01431071
12305 1933.9714  0.1958994 0.01466622
12306 1830.8154  0.1962324 0.01529496
12307        NA         NA         NA
12308        NA         NA         NA
12309        NA         NA         NA
12310        NA         NA         NA

In [47]:
final %>% filter(is.na(polity2)) %>% distinct(gwcode, gw_name)
# should only show: Abkhazia (396), South Ossetia (397), and any others 
# with genuinely no ISO3/successor convention — leave these as NA

    gwcode gw_name
1     2    United States of America
2    20    Canada
3    31    Bahamas
4    40    Cuba
5    41    Haiti
6    42    Dominican Republic
7    51    Jamaica
8    52    Trinidad and Tobago
9    53    Barbados
10   54    Dominica
11   55    Grenada
12   56    Saint Lucia
13   57    Saint Vincent and the Grenadines
14   58    Antigua & Barbuda
15   60    Saint Kitts and Nevis
16   70    Mexico
17   80    Belize
18   90    Guatemala
19   91    Honduras
20   92    El Salvador
21   93    Nicaragua
22   94    Costa Rica
23   95    Panama
24  100    Colombia
25  101    Venezuela
26  110    Guyana
27  115    Surinam
28  130    Ecuador
29  135    Peru
30  140    Brazil
⋮   ⋮      ⋮
174 771    Bangladesh
175 775    Myanmar (Burma)
176 780    Sri Lanka (Ceylon)
177 781    Maldives
178 790    Nepal
179 800    Thailand
180 811    Cambodia (Kampuchea)
181 812    Laos
182 816    Vietnam, Democratic Republic of
183 817    Vietnam, Republic of
184 820    Malaysia
185 830    Singapore
186 835    Brunei
187 840    Philippines
188 850    Indonesia
189 860    East Timor
190 900    Australia
191 910    Papua New Guinea
192 920    New Zealand
193 935    Vanuatu
194 940    Solomon Islands
195 950    Fiji
196 970    Kiribati
197 971    Nauru
198 972    Tonga
199 973    Tuvalu
200 983    Marshall Islands
201 986    Palau
202 987    Federated States of Micronesia
203 990    Samoa/Western Samoa

In [45]:
write.csv(final, "final.csv", row.names = FALSE, fileEncoding = "UTF-8")

In [ ]:
final %>%
  select(where(is.character)) %>%
  summarise(across(everything(), ~sum(!validEnc(.))))

  gw_name conflict_ids_all conflict_ids_intra conflict_ids_inter
1 117     0                0                  0

In [ ]:
?add_ucdp_acd(type = 'intrastate')

add_ucdp_acd           package:peacesciencer           R Documentation

_A_d_d _U_C_D_P _A_r_m_e_d _C_o_n_f_l_i_c_t _D_a_t_a _t_o _s_t_a_t_e-_y_e_a_r _d_a_t_a _f_r_a_m_e

_D_e_s_c_r_i_p_t_i_o_n:

     ‘add_ucdp_acd()’ allows you to add UCDP Armed Conflict data to a
     state-year data frame

_U_s_a_g_e:

     add_ucdp_acd(data, type, issue, only_wars = FALSE)

_A_r_g_u_m_e_n_t_s:

    data: state-year data frame

    type: the types of armed conflicts the user wants to consider,
          specified as a character vector. Options include
          "extrasystemic", "interstate", "intrastate", and "II". "II"
          is convenience shorthand for "internationalized intrastate".
          If you want just one (say: "intrastate"), then the type you
          want in quotes is sufficient. If you want multiple, wrap it
          in a vector with ‘c()’.

   issue: do you want to subset the data to just different armed
          conflicts over different types of issues? If so, specify
          those here as you would with the ‘type’ argument. Options
          include "territory", "government", and "both". See Details
          note in this documentation for what "both" means.

only_wars: subsets the conflict data to just those with intensity
          levels of "war" (i.e. >1,000 deaths). Defaults to FALSE.

_D_e_t_a_i_l_s:

     Right now, only state-year data are supported.

     It's worth saying that "both" in the ‘issue’ argument should not
     be understood as equivalent to ‘c("territory","government")’. The
     former is a kind of "AND" (in boolean speak) and is an explicit
     category in the data. The latter is an "OR" (in boolean speak) and
     is in all likelihood what you want if you are tempted to specify
     "both" in the ‘issue’ argument.

_V_a_l_u_e:

     ‘add_ucdp_acd()’ takes a state-year data frame and returns
     state-year information from the UCDP Armed Conflict data set (v.
     25.1). The variables returned are whether there is an ongoing
     armed conflict in that year, whether there was an armed conflict
     episode onset that year, what was the maximum intensity observed
     that year (if an armed conflict was observed), and a character
     vector of the associated conflict IDs that year.

_A_u_t_h_o_r(_s):

     Steven V. Miller

_R_e_f_e_r_e_n_c_e_s:

     Gleditsch, Nils Petter; Peter Wallensteen, Mikael Eriksson,
     Margareta Sollenberg, and Havard Strand. 2002. "Armed Conflict
     1946–2001: A New Dataset." _Journal of Peace Research_ 39(5):
     615–637.

     Davies, Shawn, Therése PEttersson, Margareta Sollenberg, and
     Magnus Öberg. 2025. "Organized violence 1989–2024, and the
     challenges of identifying civilian victims." _Journal of Peace
     Research_ 62(4): 1223-1240.

_E_x_a_m_p_l_e_s:

     # just call `library(tidyverse)` at the top of the your script.
     library(magrittr)
     library(dplyr)

     create_stateyears(system = "gw", subset_years = c(1946:2024)) %>%
      add_ucdp_acd()

     create_stateyears(system = "gw", subset_years = c(1946:2024)) %>%
      add_ucdp_acd(type = 'intrastate', issue = 'government')

In [4]:
install.packages("countrycode")

Installing package into ‘/Users/fyodorshafranov/Library/R/arm64/4.5/library’
(as ‘lib’ is unspecified)

The downloaded binary packages are in
	/var/folders/13/671_v3jd3fb5x5kcvpwmqz800000gn/T//RtmpfkmoYh/downloaded_packages

In [5]:
library(countrycode)
data(codelist_panel)
codelist_panel$year

    [1] 1789 1790 1791 1792 1793 1794 1795 1796 1797 1798 1799 1800 1801 1802
   [15] 1803 1804 1805 1806 1807 1808 1809 1810 1811 1812 1813 1814 1815 1816
   [29] 1817 1818 1819 1820 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830
   [43] 1831 1832 1833 1834 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844
   [57] 1845 1846 1847 1848 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858
   [71] 1859 1860 1861 1862 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872
   [85] 1873 1874 1875 1876 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886
   [99] 1887 1888 1889 1890 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900
  [113] 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914
  [127] 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928
  [141] 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942
  [155] 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956
  [169] 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970
  [183] 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984
  [197] 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998
  [211] 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012
  [225] 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1912 1913
  [239] 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
  [253] 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
  [267] 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
  [281] 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
  [295] 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
  [309] 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
  [323] 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
  [337] 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1816
  [351] 1817 1818 1819 1820 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830
  [365] 1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
  [379] 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
  [393] 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
  [407] 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
  [421] 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
  [435] 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
  [449] 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
  [463] 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
  [477] 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1993
  [491] 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007
  [505] 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 1900
  [519] 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914
  [533] 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928
  [547] 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942
  [561] 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956
  [575] 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970
  [589] 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984
  [603] 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998
  [617] 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012
  [631] 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1981 1982
  [645] 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996
  [659] 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010
  [673] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 1789 1790 1791 1792
  [687] 1793 1794 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806
  [701] 1807 1808 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820
  [715] 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834
  [729] 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848
  [743] 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862
  [757] 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876
  [771] 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890
  [785] 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904
  [799] 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918
  [813] 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932
  [827] 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946
  [841] 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960
  [855] 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974
  [869] 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988
  [883] 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002
  [897] 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016
  [911] 2017 2018 2019 2020 2021 2022 2023 2024 1990 1991 1992 1993 1994 1995
  [925] 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009
  [939] 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023
  [953] 2024 1789 1790 1791 1792 1793 1794 1795 1796 1797 1798 1799 1800 1801
  [967] 1802 1803 1804 1805 1806 1807 1808 1809 1810 1811 1812 1813 1814 1815
  [981] 1816 1817 1818 1819 1820 1821 1822 1823 1824 1825 1826 1827 1828 1829
  [995] 1830 1831 1832 1833 1834 1835 1836 1837 1838 1839 1840 1841 1842 1843
 [1009] 1844 1845 1846 1847 1848 1849 1850 1851 1852 1853 1854 1855 1856 1857
 [1023] 1858 1859 1860 1861 1862 1863 1864 1865 1866 1867 1868 1869 1870 1871
 [1037] 1872 1873 1874 1875 1876 1877 1878 1879 1880 1881 1882 1883 1884 1885
 [1051] 1886 1887 1888 1889 1890 1891 1892 1893 1894 1895 1896 1897 1898 1899
 [1065] 1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
 [1079] 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
 [1093] 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
 [1107] 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
 [1121] 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
 [1135] 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 [1149] 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 [1163] 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 [1177] 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1789
 [1191] 1790 1791 1792 1793 1794 1795 1796 1797 1798 1799 1800 1801 1802 1803
 [1205] 1804 1805 1806 1807 1808 1809 1810 1811 1812 1813 1814 1815 1816 1817
 [1219] 1818 1819 1820 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831
 [1233] 1832 1833 1834 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845
 [1247] 1846 1847 1848 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859
 [1261] 1860 1861 1862 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873
 [1275] 1874 1875 1876 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886 1887
 [1289] 1888 1889 1890 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900 1901
 [1303] 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915
 [1317] 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929
 [1331] 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943
 [1345] 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957
 [1359] 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971
 [1373] 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985
 [1387] 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999
 [1401] 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 [1415] 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1816 1817 1818
 [1429] 1819 1820 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832
 [1443] 1833 1834 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846
 [1457] 1847 1848 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860
 [1471] 1861 1862 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874
 [1485] 1875 1876 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888
 [1499] 1889 1890 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902
 [1513] 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916
 [1527] 1917 1918 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001
 [1541] 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015
 [1555] 2016 2017 2018 2019 2020 2021 2022 2023 2024 1789 1790 1791 1792 1793
 [1569] 1794 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807
 [1583] 1808 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821
 [1597] 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835
 [1611] 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848 1849
 [1625] 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862 1863
 [1639] 1864 1865 1866 1867 1868 1869 1870 1871 1973 1974 1975 1976 1977 1978
 [1653] 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992
 [1667] 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006
 [1681] 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 [1695] 1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
 [1709] 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
 [1723] 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
 [1737] 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
 [1751] 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
 [1765] 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 [1779] 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 [1793] 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 [1807] 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1971
 [1821] 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985
 [1835] 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999
 [1849] 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 [1863] 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1900 1901 1902
 [1877] 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916
 [1891] 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930
 [1905] 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944
 [1919] 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958
 [1933] 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972
 [1947] 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986
 [1961] 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000
 [1975] 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 [1989] 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1789 1790 1791 1792
 [2003] 1793 1794 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806
 [2017] 1807 1808 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820
 [2031] 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834
 [2045] 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848
 [2059] 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862
 [2073] 1863 1864 1865 1866 1867 1868 1869 1870 1871 1990 1991 1992 1993 1994
 [2087] 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008
 [2101] 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022
 [2115] 2023 2024 1789 1790 1791 1792 1793 1794 1795 1830 1831 1832 1833 1834
 [2129] 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848
 [2143] 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862
 [2157] 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876
 [2171] 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890
 [2185] 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904
 [2199] 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918
 [2213] 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932
 [2227] 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946
 [2241] 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960
 [2255] 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974
 [2269] 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988
 [2283] 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002
 [2297] 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016
 [2311] 2017 2018 2019 2020 2021 2022 2023 2024 1981 1982 1983 1984 1985 1986
 [2325] 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000
 [2339] 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 [2353] 2015 2016 2017 2018 2019 2020 1900 1901 1902 1903 1904 1905 1906 1907
 [2367] 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921
 [2381] 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935
 [2395] 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949
 [2409] 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963
 [2423] 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977
 [2437] 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991
 [2451] 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005
 [2465] 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019
 [2479] 2020 2021 2022 2023 2024 1900 1901 1902 1903 1904 1905 1906 1907 1908
 [2493] 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 1922
 [2507] 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935 1936
 [2521] 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950
 [2535] 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964
 [2549] 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978
 [2563] 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992
 [2577] 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006
 [2591] 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 [2605] 2021 2022 2023 2024 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834
 [2619] 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848
 [2633] 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862
 [2647] 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876
 [2661] 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890
 [2675] 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904
 [2689] 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918
 [2703] 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932
 [2717] 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946
 [2731] 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960
 [2745] 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974
 [2759] 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988
 [2773] 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002
 [2787] 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016
 [2801] 2017 2018 2019 2020 2021 2022 2023 2024 1992 1993 1994 1995 1996 1997
 [2815] 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 [2829] 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1900
 [2843] 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914
 [2857] 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928
 [2871] 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942
 [2885] 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956
 [2899] 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970
 [2913] 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984
 [2927] 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998
 [2941] 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012
 [2955] 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1789 1790
 [2969] 1791 1792 1793 1794 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804
 [2983] 1805 1806 1807 1808 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818
 [2997] 1819 1820 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832
 [3011] 1833 1834 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846
 [3025] 1847 1848 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860
 [3039] 1861 1862 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874
 [3053] 1875 1876 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888
 [3067] 1889 1890 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902
 [3081] 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916
 [3095] 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930
 [3109] 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944
 [3123] 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958
 [3137] 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972
 [3151] 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986
 [3165] 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000
 [3179] 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 [3193] 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 1984 1985 1986 1987
 [3207] 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001
 [3221] 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015
 [3235] 2016 2017 2018 2019 2020 1789 1790 1791 1792 1793 1794 1795 1796 1797
 [3249] 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807 1813 1814 1815 1816
 [3263] 1817 1818 1819 1820 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830
 [3277] 1831 1832 1833 1834 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844
 [3291] 1845 1846 1847 1848 1849 1850 1851 1852 1853 1854 1855 1856 1857 1858
 [3305] 1859 1860 1861 1862 1863 1864 1865 1866 1867 1878 1879 1880 1881 1882
 [3319] 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892 1893 1894 1895 1896
 [3333] 1897 1898 1899 1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910
 [3347] 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924
 [3361] 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938
 [3375] 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952
 [3389] 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966
 [3403] 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980
 [3417] 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994
 [3431] 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008
 [3445] 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022
 [3459] 2023 2024 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930
 [3473] 1931 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959
 [3487] 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973
 [3501] 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987
 [3515] 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001
 [3529] 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015
 [3543] 2016 2017 2018 2019 2020 2021 2022 2023 2024 1916 1917 1918 1919 1920
 [3557] 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934
 [3571] 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948

In [6]:
library(dplyr)
library(tidyr)

codelist_panel_filled <- codelist_panel %>%
  arrange(country.name.en, year) %>%
  group_by(country.name.en) %>%
  fill(everything(), .direction = "down") %>%
  ungroup()

In [7]:
nrow(codelist_panel)

[1] 29574

In [8]:
max_year <- max(codelist_panel_filled$year, na.rm = TRUE)
template <- codelist_panel_filled[codelist_panel_filled$year == max_year, ]

missing_years <- (max_year + 1):2026
extended <- do.call(rbind, lapply(missing_years, function(y) {
  rows <- template
  rows$year <- y
  rows
}))

codelist_panel_ext <- rbind(codelist_panel_filled, extended)
nrow(codelist_panel_ext)  # sanity check: should be nrow(codelist_panel) + 5 * nrow(template)

[1] 29930

In [9]:
nrow(codelist_panel)

[1] 29574

In [10]:
# has iso3c, gwc, gwn, cowc, cown, etc. -- one row per country-YEAR
write.csv(codelist_panel_ext, "codelist_panel.csv", row.names = FALSE)

states

In [11]:
install.packages("states")

Installing package into ‘/Users/fyodorshafranov/Library/R/arm64/4.5/library’
(as ‘lib’ is unspecified)

The downloaded binary packages are in
	/var/folders/13/671_v3jd3fb5x5kcvpwmqz800000gn/T//RtmpfkmoYh/downloaded_packages

In [12]:
install.packages("DT")

Installing package into ‘/Users/fyodorshafranov/Library/R/arm64/4.5/library’
(as ‘lib’ is unspecified)

The downloaded binary packages are in
	/var/folders/13/671_v3jd3fb5x5kcvpwmqz800000gn/T//RtmpfkmoYh/downloaded_packages

In [13]:
library(states)
library(DT)

Attaching package: ‘states’


The following object is masked from ‘package:readr’:

    parse_date

In [ ]:
data(gwstates)

data(cowstates)

HTML widgets cannot be represented in plain text (need html)

In [18]:
write.csv(gwstates, "gwstates.csv", row.names = FALSE)
write.csv(cowstates, "cowstates.csv", row.names = FALSE)

In [19]:
max_year <- max(codelist_panel_ext$year, na.rm = TRUE)  # e.g. 2026

gwstates_prepped <- gwstates %>%
  mutate(
    iso3c = countrycode(country_name, "country.name", "iso3c"),
    start_year = as.integer(format(start, "%Y")),
    end_year   = pmin(as.integer(format(end, "%Y")), max_year)  # cap 9999-12-31 spells
  ) %>%
  filter(!is.na(iso3c), !is.na(start_year), !is.na(end_year))

Warning message:
“There were 2 warnings in `mutate()`.
The first warning was:
ℹ In argument: `iso3c = countrycode(country_name, "country.name", "iso3c")`.
Caused by warning:
! Some values were not matched unambiguously: Abkhazia, Austria-Hungary, Baden, Bavaria, Czechoslovakia, German Democratic Republic, Hanover, Hesse-Darmstadt (Ducal), Hesse-Kassel (Electoral), Kosovo, Mecklenburg-Schwerin, Modena, Orange Free State, Parma, Saxony, South Ossetia, Tibet, Transvaal, Tuscany, Two Sicilies, United Provinces of Central America, Vietnam (Annam/Cochin China/Tonkin), Wurttemberg, Yemen (Arab Republic of Yemen), Yemen, People's Republic of, Yugoslavia, Zanzibar
To fix unmatched values, please use the `custom_match` argument. If you think the default matching rules should be improved, please file an issue at https://github.com/vincentarelbundock/countrycode/issues
ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning.”